name: CI
on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        scala: ["2.12.12"]
        spark: ["3.0.1"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: olafurpg/setup-scala@v10
      - name: Test
        run: sbt -Dspark.testVersion=${{ matrix.spark  }} ++${{ matrix.scala }} test
